# Generated by Django 2.2.5 on 2019-10-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('Id_Admin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Primer_Apellido', models.CharField(max_length=35)),
                ('Segundo_Apellido', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('Celular', models.CharField(max_length=35)),
                ('Mail', models.CharField(max_length=35)),
                ('Clave', models.CharField(default='00000', max_length=35)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Id_Cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Primer_Apellido', models.CharField(max_length=35)),
                ('Segundo_Apellido', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('Celular', models.CharField(max_length=35)),
                ('Mail', models.CharField(max_length=35)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('Id_Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionServiMax.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('Id_Trabajador', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Primer_Apellido', models.CharField(max_length=35)),
                ('Segundo_Apellido', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('Celular', models.CharField(max_length=35)),
                ('Mail', models.CharField(max_length=35)),
                ('Clave', models.CharField(default='00000', max_length=35)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('Id_Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionServiMax.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('ID_Transaccion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Fecha', models.CharField(max_length=10)),
                ('Tipo', models.CharField(default='C', max_length=1)),
                ('ID_Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionServiMax.Administrador')),
                ('ID_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionServiMax.Cliente')),
                ('ID_Trabajadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionServiMax.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='TiempoLaborado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('horas', models.CharField(max_length=2)),
                ('minutos', models.CharField(max_length=2)),
                ('segundos', models.CharField(max_length=4)),
                ('Id_Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionServiMax.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id_Producto', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Precio_De_Compra', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Precio_De_Venta', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Tipo', models.CharField(choices=[('J', 'Joya'), ('P', 'Producto')], default='M', max_length=1)),
                ('Kilates', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('Kilogramos', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('ID_Transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionServiMax.Transaccion')),
            ],
        ),
    ]
