# Generated by Django 2.2.5 on 2019-10-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiMax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='Clave',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Clave',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='Clave',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
