# Generated by Django 2.2.5 on 2019-11-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiMax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempolaborado',
            name='minutos',
        ),
        migrations.RemoveField(
            model_name='tiempolaborado',
            name='segundos',
        ),
        migrations.AlterField(
            model_name='tiempolaborado',
            name='horas',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
