# Generated by Django 2.2.5 on 2019-10-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiMax', '0002_auto_20191013_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='Clave',
            field=models.CharField(default='00000', max_length=35),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Clave',
            field=models.CharField(default='00000', max_length=35),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='Clave',
            field=models.CharField(default='00000', max_length=35),
        ),
    ]
