# Generated by Django 2.2.5 on 2019-11-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiMax', '0003_auto_20191106_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.CharField(default='', max_length=10)),
                ('Nombre', models.CharField(max_length=20)),
                ('Precio_De_Compra', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Precio_De_Venta', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Ganacia', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
