# Generated by Django 2.2.5 on 2019-10-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiMax', '0003_auto_20191013_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Clave',
        ),
    ]
