# Generated by Django 2.2.5 on 2019-10-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiMax', '0004_remove_cliente_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoLabporado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('horas', models.CharField(max_length=2)),
                ('minutos', models.CharField(max_length=2)),
                ('segundos', models.CharField(max_length=4)),
                ('Id_Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionServiMax.Trabajador')),
            ],
        ),
    ]
