# Generated by Django 2.2.6 on 2019-10-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiMax', '0004_remove_cliente_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='Fecha',
            field=models.CharField(max_length=10),
        ),
    ]
