# Generated by Django 2.2.5 on 2019-10-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiMax', '0005_tiempolabporado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiempoLabporado',
            new_name='TiempoLaborado',
        ),
    ]
