# Generated by Django 2.2.6 on 2019-10-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionServiMax', '0006_auto_20191018_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Id_Cliente',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
